---
- hosts: localhost # using ansible-pull so will run locally on the machine that calls this
  connection: local # using ansible-pull so will run locally on the machine that calls this and pulls from github, could be SSH
  become: true # used to enable sudo

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: install packages
    package: # ansible module to use for this task
      name: 
        # utilities
        - baobab
        - balena-etcher
        - bleachbit
        - curl
        - freefilesync
        - gnome-disk-utility
        - gparted
        - grsync
        - hardinfo
        - htop
        - keepassxc
        - nextcloud-client
        - openssh-server
        - remmina
        - tlp
        - tmux
        # media
        - drawing
        - calibre
        - kolourpaint
        - pinta
        - puddletag
        - rhythmbox
        - vlc

  - name: copy wallpaper file
    copy: 
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    dconf: # ansible module to use for this task
      key: # 44:44 in this video https://www.youtube.com/watch?v=gIDywsGBqf4