---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Remove system dconf database file
      file:
        path: /etc/dconf/db/local.d/00-desktop-settings
        state: absent

    - name: Create minimal safe dconf profile (don't delete it completely)
      copy:
        content: |
          user-db:user
        dest: /etc/dconf/profile/user
        mode: '0644'

    - name: Update dconf database to apply changes
      command: dconf update

    - name: Reset user dconf settings that were applied system-wide
      shell: |
        # Reset all the keys that were set in the system profile
        dconf reset /org/nemo/desktop/computer-icon-visible
        dconf reset /org/nemo/desktop/home-icon-visible
        dconf reset /org/nemo/desktop/network-icon-visible
        dconf reset /org/nemo/desktop/trash-icon-visible
        dconf reset /org/nemo/desktop/volumes-visible
        dconf reset /org/nemo/preferences/default-folder-viewer
        dconf reset /org/nemo/preferences/default-view
        dconf reset /org/nemo/preferences/default-sort-order
        dconf reset /org/nemo/preferences/default-sort-in-reverse
        dconf reset /org/nemo/list-view/default-zoom-level
        dconf reset /org/x/editor/preferences/editor/scheme
        dconf reset /org/cinnamon/desktop/keybindings/media-keys/shutdown
        dconf reset /org/cinnamon/desktop/keybindings/media-keys/logout
        dconf reset /org/cinnamon/desktop/keybindings/media-keys/terminal
        dconf reset /org/cinnamon/desktop/keybindings/media-keys/www
        dconf reset /org/cinnamon/desktop/keybindings/media-keys/screensaver
        dconf reset /org/cinnamon/desktop/keybindings/media-keys/video-rotation-lock
        dconf reset /org/cinnamon/desktop/keybindings/looking-glass-keybinding
        dconf reset /org/cinnamon/desktop/keybindings/custom-list
        dconf reset -f /org/cinnamon/desktop/keybindings/custom-keybindings/
      become: false
      become_user: "{{ gui_user }}"
      ignore_errors: yes

    - name: Clear Nemo caches and metadata (as user)
      shell: |
        pkill -f nemo || true
        sleep 1
        rm -f /home/{{ gui_user }}/.config/nemo/desktop-metadata || true
        rm -rf /home/{{ gui_user }}/.local/share/gvfs-metadata || true
        rm -rf /home/{{ gui_user }}/.cache/nemo || true
      become: false
      become_user: "{{ gui_user }}"
      ignore_errors: yes

    - name: Display completion message
      debug:
        msg: |
          Cleanup complete! The system dconf profile has been safely reset.
          Please log out and log back in, then run your user-level playbook.
          DO NOT DELETE /etc/dconf/profile/user - it's needed for the desktop environment.
