---
- hosts: localhost
  connection: local
  become: true

# list of config file paths
  vars:
    files_to_copy:
      - src: files/configs/config/bleachbit/bleachbit.ini
        dest: /home/jack/.config/bleachbit/bleachbit.ini
        owner: jack
        group: jack
        mode: "0664"
      - src: files/configs/config/vlc/vlcrc
        dest: /home/jack/.config/vlc/vlcrc
        owner: jack
        group: jack
        mode: "0600"

  tasks:

    #### APPLICATIONS ####

    - name: Update and upgrade apt packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400

    - name: Add sublime-text apt-key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add sublime-text apt repo
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present
        filename: sublime-text
        update_cache: yes

    - name: install apt packages
      package: # ansible module to use for this task
        name: 
          # utilities
          - baobab # disk usage analyser
          - bleachbit # cleaning utility
          - curl
          - freefilesync
          - gdebi-core # required dependency for installing .deb files, likely already satisfied by default
          - gnome-disk-utility # disks
          - gparted
          - grsync
          - hardinfo # gui hardware overview
          - htop
          - keepassxc
          - nextcloud-desktop
          - openssh-server
          - remmina # remote desktop client
          - sublime-text
          - tlp # battery optimisation
          - tmux # advanced terminal
          # media
          - drawing # paint clone
          - calibre # ebook manager
          - puddletag
          - rhythmbox
          - vlc
        state: present

    - name: Install snap packages
      community.general.snap:
        name:
          - pinta

    #### OS SETTINGS ####

    - name: Copy wallpaper file
      copy:
        src: files/wallpapers/spectrum_curves.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg
        owner: root
        group: root

    #### CONFIG FILES ####

    - name: Ensure destination directories exist and set permissions
      file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ files_to_copy }}"
      loop_control:
        label: "{{ item.dest }}"

    - name: Copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ files_to_copy }}"
      loop_control:
        label: "{{ item.src }}"
