---
- hosts: localhost
  connection: local
  # NO become: true - run as regular user

  tasks:
    - name: Set Nemo desktop icons preferences
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/nemo/desktop/computer-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/home-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/network-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/trash-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/volumes-visible", value: "false" }

    - name: Set Nemo file browser defaults
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/nemo/preferences/default-folder-viewer", value: "'list-view'" }
        - { key: "/org/nemo/preferences/default-view", value: "'list-view'" }
        - { key: "/org/nemo/preferences/default-sort-order", value: "'name'" }
        - { key: "/org/nemo/preferences/default-sort-in-reverse", value: "false" }

    - name: Set Nemo list view settings
      dconf:
        key: "/org/nemo/list-view/default-zoom-level"
        value: "'smaller'"

    - name: Set text editor theme
      dconf:
        key: "/org/x/editor/preferences/editor/scheme"
        value: "'oblivion'"

    - name: Set Cinnamon media key bindings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/shutdown", value: "['<Primary><Alt>Delete', 'XF86PowerOff']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/logout", value: "['<Primary><Alt>End']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/terminal", value: "['<Primary><Alt>t', '<Super>t']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/www", value: "['<Primary><Alt>w', '<Super>w']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/screensaver", value: "['<Primary><Alt>l', '<Super>l']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/video-rotation-lock", value: "@as []" }

    - name: Disable looking glass keybinding
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/looking-glass-keybinding", value: "@as []" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-list", value: "['custom0', 'custom1', 'custom2', 'custom3', 'custom5']" }

    - name: Set custom keybinding - KeepassXC
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/binding", value: "['<Super>k', '<Primary><Alt>k']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/command", value: "'keepassxc %f'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/name", value: "'KeepassXC'" }

    - name: Set custom keybinding - Text editor
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/binding", value: "['<Super>n', '<Primary><Alt>n']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/command", value: "'xed'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/name", value: "'Text editor'" }

    - name: Set custom keybinding - VLC
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/binding", value: "['<Primary><Alt>v', '<Super>v']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/command", value: "'/usr/bin/vlc'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/name", value: "'VLC'" }

    - name: Set custom keybinding - Finamp
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/binding", value: "['<Primary><Alt>f', '<Super>f']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/command", value: "'/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=finamp com.unicornsonlsd.finamp'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/name", value: "'Finamp'" }

    - name: Set custom keybinding - Obsidian
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom5/binding", value: "['<Primary><Alt>o', '<Super>o']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom5/command", value: "'/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom5/name", value: "'Obsidian'" }

    - name: Reset Nemo folder view preferences to apply default list view
      shell: |
        pkill -f nemo || true
        sleep 1
        rm -f ~/.config/nemo/desktop-metadata || true
        rm -rf ~/.local/share/gvfs-metadata || true
        rm -rf ~/.cache/nemo || true
      ignore_errors: yes
