---
- hosts: localhost # using ansible-pull so will run locally on the machine that calls this
  connection: local # using ansible-pull so will run locally on the machine that calls this and pulls from github, could be SSH
  become: true # used to enable sudo

  tasks:

#### APPLICATIONS ####

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: add sublime-text apt-key
    apt_key: 
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: add sublime-text apt repo
    apt_repository: 
      repo: deb https://download.sublimetext.com/ apt/stable/
      state: present
      filename: sublime-text
      update_cache: yes

  - name: install apt packages
    package: # ansible module to use for this task
      name: 
        # utilities
        - baobab # disk usage analyser
#        - balena-etcher # not in a repo
        - bleachbit # cleaning utility
        - curl
        - freefilesync
        - gdebi-core # required dependency for installing .deb files, likely already satisfied by default
        - gnome-disk-utility # disks
        - gparted
        - grsync
        - hardinfo # gui hardware overview
        - htop
        - keepassxc
        - nextcloud-desktop
        - openssh-server
        - remmina # remote desktop client
        - sublime-text
        - tlp # battery optimisation
        - tmux # advanced terminal
        # media
        - drawing # paint clone
        - calibre # ebook manager
        - puddletag
        - rhythmbox
        - vlc
      state: present

  - name: install snap packages
    community.general.snap: 
      name: 
        pinta # paint.net clone

#### OS SETTINGS ####

  - name: copy wallpaper file
    copy: 
      src: files/wallpapers/spectrum_curves.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

#### CONFIG FILES ####

  - vars:
      files_to_copy:
        - src: files/configs/config/bleachbit
          dest: /home/jack/.config/
          owner: jack
          group: jack
          mode: 664
        - src: files/configs/config/vlc
          dest: /home/jack/.config/
          owner: jack
          group: jack
          mode: 600

  - name: ensure destination directories exist and set permissions
    file:
      path: "{{ item.dest | dirname }}"
      state: directory
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    loop: "{{ files_to_copy }}"

  - name: copy config files
    copy: 
      src: "{{ item.src }}" 
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    loop: "{{ files_to_copy }}"


#  - name: set wallpaper
#    dconf: # ansible module to use for this task
#      key: # 44:44 in this video https://www.youtube.com/watch?v=gIDywsGBqf4
