---
- hosts: localhost
  connection: local
  become: true

# list of config file paths
  vars:
    files_to_copy:
      - src: files/home/config/bleachbit/bleachbit.ini
        dest: /home/jack/.config/bleachbit/bleachbit.ini
        owner: jack
        group: jack
        mode: "0664"
      - src: files/home/config/vlc/vlcrc
        dest: /home/jack/.config/vlc/vlcrc
        owner: jack
        group: jack
        mode: "0600"

  tasks:

    #### APPLICATIONS ####

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Add sublime-text GPG key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Download Signal messenger GPG key
      ansible.builtin.get_url:
        url: https://updates.signal.org/desktop/apt/keys.asc
        dest: /tmp/signal.asc

    - name: Convert Signal messenger GPG key to keyring format
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/signal-desktop-keyring.gpg /tmp/signal.asc
      args:
        creates: /usr/share/keyrings/signal-desktop-keyring.gpg

    - name: Download VSCodium GPG key
      ansible.builtin.get_url:
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        dest: /tmp/vscodium.gpg

    - name: Convert VSCodium GPG key to keyring format
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/vscodium-archive-keyring.gpg /tmp/vscodium.gpg
      args:
        creates: /usr/share/keyrings/vscodium-archive-keyring.gpg

    - name: Add multiple custom repositories
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: present
        filename: "{{ item.filename | default(omit) }}"
        update_cache: "{{ item.update_cache | default(false) }}"
      loop:
        # Sublime text
        - repo: deb https://download.sublimetext.com/ apt/stable/
          state: present
          filename: sublime-text
          update_cache: yes
        # vs codium
        - repo: "deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs/ vscodium main"
          state: present
          filename: vscodium
          update_cache: yes
        # CoBang QR scanner
        - repo: "ppa:ng-hong-quan/ppa"
          update_cache: true
        # Signal
        - repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
          state: present
          filename: signal
          update_cache: true

    - name: install all apt packages
      package: # ansible module to use for this task
        name: 
          # utilities
          - baobab # disk usage analyser
          - bleachbit # cleaning utility
          - cobang # repo added above
          - codium # repo added above
          - curl
          - freefilesync
          - gdebi-core # required dependency for installing .deb files, likely already satisfied by default
          - gnome-disk-utility # disks
          - gparted
          - grsync
          - hardinfo # gui hardware overview
          - htop
          - keepassxc
          - nextcloud-desktop
          - openssh-server
          - remmina # remote desktop client
          - signal-desktop # repo added above
          - sublime-text # repo added above
          - tlp # battery optimisation
          - tmux # advanced terminal
          # media
          - drawing # paint clone
          - calibre # ebook manager
          - puddletag
          - rhythmbox
          - vlc
        state: present

    - name: Install snap packages
      community.general.snap:
        name:
          - pinta

    #### OS SETTINGS ####

    - name: Copy wallpaper file
      copy:
        src: files/wallpapers/spectrum_curves.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg
        owner: root
        group: root

    #### CONFIG FILES ####

    - name: Ensure destination directories exist and set permissions
      file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0755"
      loop: "{{ files_to_copy }}"
      loop_control:
        label: "{{ item.dest }}"

    - name: Copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ files_to_copy }}"
      loop_control:
        label: "{{ item.src }}"
