---
- hosts: localhost # using ansible-pull so will run locally on the machine that calls this
  connection: local # using ansible-pull so will run locally on the machine that calls this and pulls from github, could be SSH
  become: true # used to enable sudo

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: add sublime-text apt-key
    apt_key: 
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: add sublime-text apt repo
    apt_repository: 
      repo: deb https://download.sublimetext.com/ apt/stable/
      state: present
      filename: sublime-text
      update_cache: yes

  - name: install apt packages
    package: # ansible module to use for this task
      name: 
        # utilities
        - baobab # disk usage analyser
#        - balena-etcher # not in a repo
        - bleachbit # cleaning utility
        - curl
        - freefilesync
        - gnome-disk-utility # disks
        - gparted
        - grsync
        - hardinfo # gui hardware overview
        - htop
        - keepassxc
        - nextcloud-desktop
        - openssh-server
        - remmina # remote desktop client
        - sublime-text
        - tlp # battery optimisation
        - tmux # advanced terminal
        # media
        - drawing # paint clone
        - calibre # ebook manager
        - puddletag
        - rhythmbox
        - vlc

  - name: install snap packages
    community.general.snap: 
      name: 
        pinta # paint.net clone

  - name: copy wallpaper file
    copy: 
      src: files/wallpapers/spectrum_curves.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

#  - name: set wallpaper
#    dconf: # ansible module to use for this task
#      key: # 44:44 in this video https://www.youtube.com/watch?v=gIDywsGBqf4
