---
- hosts: localhost # using ansible-pull so will run locally on the machine that calls this
  connection: local # using ansible-pull so will run locally on the machine that calls this and pulls from github, could be SSH
  become: true # used to enable sudo

  tasks:
  - name: install packages
    package: # ansible module to use for this task
      name: 
        - htop
        - tmux
        - curl
  - name: copy wallpaper file
    copy: 
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    dconf: # ansible module to use for this task
      key: # 44:44 in this video https://www.youtube.com/watch?v=gIDywsGBqf4