---
- hosts: localhost
  connection: local
  gather_facts: yes  # Needed for ansible_date_time and ansible_env
  name: Configure cinnamon settings
  # NO become: true - run as regular user

  vars:
    # Default pinned apps - override in group_vars/host_vars as needed
    cinnamon_pinned_apps:
      - "firefox.desktop"
      - "org.keepassxc.KeePassXC.desktop"
      - "com.unicornsonlsd.finamp.desktop:flatpak"
      - "md.obsidian.Obsidian.desktop:flatpak"
      - "org.x.editor.desktop"
    
    # Show application names on taskbar buttons
    cinnamon_title_display: 2
    # Optional: customize other settings if needed
    # cinnamon_show_thumbnails: true
    # cinnamon_thumbnail_size: 6

    # Terminal profile settings
    terminal_profile_id: "b1dcc9dd-5262-4d8d-a863-c897e6d979b9"
    # to extract any terminal settings set by user:
    # dconf dump /org/gnome/terminal/legacy/profiles:/ > terminal-settings.dconf && cat terminal-settings.dconf

  tasks:
    - name: Set Nemo desktop icons preferences
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/nemo/desktop/computer-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/home-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/network-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/trash-icon-visible", value: "false" }
        - { key: "/org/nemo/desktop/volumes-visible", value: "false" }

    - name: Set Nemo file browser defaults
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/nemo/preferences/default-folder-viewer", value: "'list-view'" }
        - { key: "/org/nemo/preferences/default-view", value: "'list-view'" }
        - { key: "/org/nemo/preferences/default-sort-order", value: "'name'" }
        - { key: "/org/nemo/preferences/default-sort-in-reverse", value: "false" }

    - name: Set Nemo list view settings
      dconf:
        key: "/org/nemo/list-view/default-zoom-level"
        value: "'smaller'"

    - name: Set text editor theme
      dconf:
        key: "/org/x/editor/preferences/editor/scheme"
        value: "'oblivion'"

    - name: Set GNOME Terminal profile list
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/list"
        value: "['{{ terminal_profile_id }}']"

    - name: Set GNOME Terminal default profile
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/default"
        value: "'{{ terminal_profile_id }}'"

    - name: Configure GNOME Terminal profile settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile_id }}/default-size-columns", value: "90" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile_id }}/default-size-rows", value: "23" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile_id }}/font", value: "'Monospace 13'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile_id }}/use-system-font", value: "false" }

    - name: Set Cinnamon media key bindings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/shutdown", value: "['<Primary><Alt>Delete', 'XF86PowerOff']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/logout", value: "['<Primary><Alt>End']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/terminal", value: "['<Primary><Alt>t', '<Super>t']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/www", value: "['<Primary><Alt>w', '<Super>w']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/screensaver", value: "['<Primary><Alt>l', '<Super>l']" }
        - { key: "/org/cinnamon/desktop/keybindings/media-keys/video-rotation-lock", value: "@as []" }

    - name: Disable looking glass keybinding
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/looking-glass-keybinding", value: "@as []" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-list", value: "['custom0', 'custom1', 'custom2', 'custom3', 'custom4', 'custom5']" }

    - name: Set custom keybinding - KeepassXC
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/binding", value: "['<Super>k', '<Primary><Alt>k']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/command", value: "'keepassxc %f'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/name", value: "'KeepassXC'" }

    - name: Set custom keybinding - Text editor
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/binding", value: "['<Primary><Alt>n']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/command", value: "'xed'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/name", value: "'Text editor'" }

    - name: Set custom keybinding - VLC
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/binding", value: "['<Primary><Alt>v', '<Super>v']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/command", value: "'/usr/bin/vlc'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/name", value: "'VLC'" }

    - name: Set custom keybinding - Finamp
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/binding", value: "['<Primary><Alt>f', '<Super>f']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/command", value: "'/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=finamp com.unicornsonlsd.finamp'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/name", value: "'Finamp'" }

    - name: Set custom keybinding - BleachBit
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom4/binding", value: "['<Super>b', '<Primary><Alt>b']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom4/command", value: "'bleachbit'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom4/name", value: "'BleachBit'" }

    - name: Set custom keybinding - Obsidian
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom5/binding", value: "['<Primary><Alt>o', '<Super>o']" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom5/command", value: "'/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@'" }
        - { key: "/org/cinnamon/desktop/keybindings/custom-keybindings/custom5/name", value: "'Obsidian'" }

    - name: Reset Nemo folder view preferences to apply default list view
      shell: |
        pkill -f nemo || true
        sleep 1
        rm -f ~/.config/nemo/desktop-metadata || true
        rm -rf ~/.local/share/gvfs-metadata || true
        rm -rf ~/.cache/nemo || true
      ignore_errors: yes

    - name: Ensure Cinnamon spice config directory exists
      file:
        path: "/home/{{ gui_user }}/.config/cinnamon/spices/grouped-window-list@cinnamon.org"
        state: directory
        mode: '0755'
        owner: "{{ gui_user }}"
        group: "{{ gui_user }}"
    
    - name: Configure Cinnamon grouped-window-list settings
      template:
        src: templates/grouped-window-list.json.j2
        dest: "/home/{{ gui_user }}/.config/cinnamon/spices/grouped-window-list@cinnamon.org/2.json"
        backup: yes
        mode: '0644'
        owner: "{{ gui_user }}"
        group: "{{ gui_user }}"
