---
- name: Configure Cinnamon grouped-window-list settings
  hosts: localhost
  connection: local
  become: no
  gather_facts: yes  # Needed for ansible_date_time and ansible_env
  
  vars:
    # Default pinned apps - override in group_vars/host_vars as needed
    cinnamon_pinned_apps:
      - "firefox.desktop"
      - "org.keepassxc.KeePassXC.desktop"
      - "md.obsidian.Obsidian.desktop:flatpak"
      - "com.unicornsonlsd.finamp.desktop:flatpak"
    
    # Optional: customize other settings if needed
    # cinnamon_show_thumbnails: true
    # cinnamon_title_display: 1
    # cinnamon_thumbnail_size: 6
    
  tasks:
    - name: Ensure Cinnamon spice config directory exists
      file:
        path: "/home/{{ gui_user }}/.config/cinnamon/spices/grouped-window-list@cinnamon.org"
        state: directory
        mode: '0755'
        owner: "{{ gui_user }}"
        group: "{{ gui_user }}"
    
    - name: Configure Cinnamon grouped-window-list settings
      template:
        src: templates/grouped-window-list.json.j2
        dest: "/home/{{ gui_user }}/.config/cinnamon/spices/grouped-window-list@cinnamon.org/2.json"
        backup: yes
        mode: '0644'
        owner: "{{ gui_user }}"
        group: "{{ gui_user }}"
      notify: restart cinnamon
      
  handlers:
    - name: restart cinnamon
      shell: |
        # Restart cinnamon for the GUI user
        sudo -u {{ gui_user }} bash -c '
          export DISPLAY=:0
          if pgrep -x "cinnamon" > /dev/null; then
            nohup cinnamon --replace > /dev/null 2>&1 &
          fi
        '
      async: 10
      poll: 0
